services:
  lab01:
    build: .
    container_name: capstone-lab-01
    hostname: labsrv
    ports:
      - "2121:21"
      - "2222:22"
      - "1139:139"
      - "4445:445"
      - "40000-40100:40000-40100"
    restart: unless-stopped
